name: KIOTO
favicon: null
layout_spectrum: 0.47124
typography_spectrum: 0.90367
title: KIOTO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#939393'
    - '#4d4d4d'
    - '#000000'
    - '#d0d0d0'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.8401794077362865
purpose: []
