name: KIOTO
favicon: null
layout_spectrum: 0.76865
typography_spectrum: 0.90367
title: RAW INDUSTRIAL DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1f1f'
    - '#979797'
    - '#6a6a6a'
    - '#bebebe'
    - '#e5e5e5'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.8401794077362865
purpose: []
